### ISSUE TITLE
[Question] Can not find function 'read_point_cloud' in your code.

### ISSUE THREAD

**Issue by CaptainEven** [miguelriemoliveira/RansacPlaneDetection#3]

**Comment by miguelriemoliveira** [comment]
Hi @CaptainEven ,

where is it called? Can you tell me the script and the code line?

**Comment by CaptainEven** [comment]
@miguelriemoliveira Thanks for the quick reply! Line 106 in script test_ransac_multiplane.py.

**Comment by miguelriemoliveira** [comment]
Hi @tiagomfmadeira ,

can you help @CaptainEven with this? This line says **negativespade** which means you were the last to use it.

I suspect its a funtion from open3d, but am not sure. Can you check please?

**Comment by CaptainEven** [comment]
@miguelriemoliveira Its's OK now, the problem may be caused by API changing of Open3D, i update them in the code, and it works now! Thank again for your cues for debugging.

**Comment by miguelriemoliveira** [comment]
Great. Can you please send us a PR for this change?

**Comment by CaptainEven** [comment]
@miguelriemoliveira Hi, a PR of updating Open3D API calling is created.

**Comment by miguelriemoliveira** [comment]
Thanks, just accepted the PR.

**Comment by CaptainEven** [comment]
@miguelriemoliveira Hi, i have create a PR for adding other methods of solving a homogeneous or non-homogeneous linear equations such as over-determined, least square, PCA, SVD, please check.

**Comment by miguelriemoliveira** [comment]
Thanks. I just merged.

Regards,
Miguel

**Comment by CaptainEven** [comment]
@miguelriemoliveira Got it!
